# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-189NqMy1Pw5vle1OSUfwNQJ1y9jrr5R
"""

print("select an operation to perform")
print("1.ADDITION")
print("2.SUBTRACT")
print("3.MULTIPLY")
print("4.DIVIDE")
print("5.EXIT")

number = input("Enter a Number: ")


if number == "1":
    num1 = input("Enter 1st number: ")
    num2 = input("Enter 2nd number: ")
    print("the sum is " + str(int(num1) + int(num2)))
elif number == "2":
      num1 = input("Enter 1st number: ")
      num2 = input("Enter 2nd number: ")
      print("the sum is " + str(int(num1) - int(num2)))
elif number == "3":
      num1 = input("Enter 1st number: ")
      num2 = input("Enter 2nd number: ")
      print("the sum is " + str(int(num1) * int(num2)))
elif number == "4":
      num1 = input("Enter 1st number: ")
      num2 = input("Enter 2nd number: ")
      print("the sum is " + str(int(num1) / int(num2)))

else:
    print("Invalid Entry")

m =input("Enter a character :")
m =m.lower()
if(m=="a"or m=="e"or m=="i"or m=="o" or m=="u"):
  print("It is a vowel")
else:
  print("It is a constant")

unit= input("is this temperature in celsius or fahrenheite (C/F):")
temp = float (input("enter the temperature: "))

if unit =="C":
    temp =round ((9* temp) /5+32,1)
    print(f" the temperature in fahrenheite is: {temp}°F")
elif unit =="F":
      temp =round ((temp-32)/1.8, 1)
      print ((f" the temperature in celsius is: {temp}°C"))
else:
    print(f"{unit}is an invalid unitof mesurement")

a=int(input("Enter first number :"))
b=int(input("Enter second number :"))
c=int(input("Enter third number :"))
if (a>=b) and (a>=c):
  largest = a
elif (b>=a) and (b>=c):
  largest = b
else:
  largest = c
print("The largest number is", largest)

amount = int(input("Enter the sell price :"))
if(amount>0):
  if amount >= 100:
    dis = amount*.10
  elif amount <100:
    dis = amount*0.05
  print("Discount :",dis)
  print("Net pay :",amount-dis)
else:
  print("Invalid amount")